version: '3'

services:
  db:
    image:
      postgres:13.3-alpine
    env_file:
      - .env
    expose:
      - 5432
    restart:
      always
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      ./backend
    env_file:
      - .env
    command: >
      bash -c "alembic upgrade head
      && gunicorn app.main:app --worker-class \
      uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000"
    ports:
      - 8000:8000
    restart:
      always
    volumes:
      - zip_files:/note-taking/static
    depends_on:
      - db

  cleaner:
    build:
      ./cleaner
    command:
      python -u cleaner.py static
    volumes:
      - zip_files:/cleaner/static
    depends_on:
      - app

volumes:
  db_data:
  zip_files:
