version: '3'

services:
  db:
    image:
      postgres:13.3-alpine
    env_file:
      - .env
    expose:
      - 5432
    restart:
      always
    volumes:
      - db_data:/var/lib/postgres/data

  app:
    build:
      ./backend
    env_file:
      - .env
    command: >
      bash -c "alembic upgrade head
      && gunicorn app.main:app --worker-class \
      uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000"
    ports:
      - 8000:8000
    restart:
      always
    depends_on:
      - db

volumes:
  db_data:
